@extends('layouts.app')

@section('content')
<div class="container py-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow-sm border-0">
                <div class="card-header bg-white border-0 pt-4 pb-0">
                    <h4 class="fw-bold mb-0 text-uppercase">Buat Akun {{ strtoupper($protocol) }}</h4>
                </div>
                <div class="card-body p-4">
                    @if(session('error'))
                        <div class="alert alert-danger">{{ session('error') }}</div>
                    @endif
                    @if(session('sweet_error'))
                        <div class="alert alert-danger">{{ session('sweet_error') }}</div>
                    @endif
                    @if($errors->any())
                        <div class="alert alert-danger">
                            <ul class="mb-0">
                                @foreach($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <form action="{{ route('vpn.store', $protocol) }}" method="POST" id="createForm">
                        @csrf
                        <div class="mb-3">
                            <label class="form-label fw-bold">Username</label>
                            <input type="text" name="username" id="usernameInput" class="form-control" value="{{ old('username') }}" required>
                            <div class="form-text">Hanya huruf, angka, dot (.), dan underscore (_)</div>
                            <div id="usernameFeedback" class="mt-2" style="display: none; font-weight: bold;"></div>
                        </div>

                        @if($protocol === 'ssh')
                        <div class="mb-3">
                            <label class="form-label fw-bold">Password</label>
                            <input type="text" name="password" class="form-control" value="{{ old('password') }}" required>
                        </div>
                        @else
                        <!-- UUID will be auto-generated by the system -->
                        <input type="hidden" name="password" value="auto">
                        @endif

                        @if($protocol !== 'ssh')
                        <div class="mb-3">
                            <label class="form-label fw-bold">Custom SNI</label>
                            <select name="sni_config" class="form-select">
                                <option value="3" {{ old('sni_config', '3') == '3' ? 'selected' : '' }}>Tanpa konfigurasi (Default)</option>
                                <option value="1" {{ old('sni_config') == '1' ? 'selected' : '' }}>support.zoom.us</option>
                                <option value="2" {{ old('sni_config') == '2' ? 'selected' : '' }}>live.iflix.com</option>
                            </select>
                            <div class="form-text">Pilih profil SNI untuk konfigurasi koneksi.</div>
                        </div>
                        @endif

                        <div class="mb-3">
                            <label class="form-label fw-bold">Masa Aktif (Hari)</label>
                            <input type="hidden" name="expired" id="expiredInput" value="30">
                            <div class="d-flex flex-wrap gap-2">
                                @foreach([1, 3, 7, 14, 30, 60] as $day)
                                    <button type="button" class="btn btn-outline-primary day-btn" data-days="{{ $day }}">{{ $day }} Hari</button>
                                @endforeach
                            </div>
                        </div>

                        @if(Auth::user()->role === 'customer')
                        <div class="mb-4">
                            <div class="alert alert-info border-0 shadow-sm mb-0">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                        <h6 class="mb-1 fw-bold text-dark"><i class="fas fa-receipt me-2"></i>Total Tagihan</h6>
                                        <small class="text-dark">Harga dasar per 30 hari: Rp {{ number_format($basePrice, 0, ',', '.') }}</small>
                                    </div>
                                    <h4 class="mb-0 fw-bold text-success" id="priceDisplay">Rp 0</h4>
                                </div>
                            </div>
                        </div>
                        @endif

                        @if($protocol !== 'ssh')
                        <div class="mb-3">
                            <label class="form-label fw-bold">Quota (GB)</label>
                            <input type="number" name="quota" class="form-control" value="{{ old('quota', '0') }}" min="0">
                            <div class="form-text">Masukkan 0 untuk unlimited.</div>
                        </div>
                        @endif

                        @if(Auth::user()->role === 'admin')
                        <div class="mb-4">
                            <label class="form-label fw-bold">Limit IP</label>
                            <input type="number" name="limit_ip" id="createLimitIpInput" class="form-control" value="{{ old('limit_ip', '1') }}" min="1">
                            <div class="form-text">Jumlah maksimal IP yang dapat login bersamaan. Biarkan 1 untuk keamanan.</div>
                        </div>
                        @else
                        <div class="mb-4">
                            <label class="form-label fw-bold">Limit IP</label>
                            <input type="number" name="limit_ip" id="createLimitIpInput" class="form-control" value="{{ old('limit_ip', '1') }}" min="1" @if($maxIpLimit > 0) max="{{ $maxIpLimit }}" @endif>
                            <div class="form-text">
                                @if($maxIpLimit > 0)
                                    Maksimal {{ $maxIpLimit }} IP sesuai pengaturan admin.
                                @else
                                    Tidak ada batas maksimal dari admin.
                                @endif
                            </div>
                        </div>
                        @endif

                        <div class="d-grid gap-2">
                            <button type="submit" id="submitBtn" class="btn btn-primary btn-lg">Buat Akun</button>
                            <a href="{{ route('vpn.index', $protocol) }}" class="btn btn-light">Kembali</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const usernameInput = document.getElementById('usernameInput');
    const feedback = document.getElementById('usernameFeedback');
    const submitBtn = document.getElementById('submitBtn');
    let timeoutId;

    // Pricing Logic
    const basePrice = {{ isset($basePrice) ? $basePrice : 0 }};
    const isCustomer = {{ Auth::user()->role === 'customer' ? 'true' : 'false' }};
    const ipPrice = {{ isset($ipPrice) ? $ipPrice : 0 }};
    const priceDisplay = document.getElementById('priceDisplay');
    const expiredInput = document.getElementById('expiredInput');
    const dayBtns = document.querySelectorAll('.day-btn');
    const limitIpInput = document.getElementById('createLimitIpInput');

    function updatePrice(days) {
        expiredInput.value = days;
        dayBtns.forEach(btn => {
            if (parseInt(btn.dataset.days) === days) {
                btn.classList.add('active', 'btn-primary');
                btn.classList.remove('btn-outline-primary');
            } else {
                btn.classList.remove('active', 'btn-primary');
                btn.classList.add('btn-outline-primary');
            }
        });

        if (isCustomer && priceDisplay) {
            const ip = limitIpInput ? (parseInt(limitIpInput.value, 10) || 1) : 1;
            let total = Math.round((basePrice / 30) * days);
            total += ip > 1 ? (ipPrice * (ip - 1)) : 0;
            priceDisplay.textContent = 'Rp ' + new Intl.NumberFormat('id-ID').format(total);
        }
    }

    // Default select 30 days
    updatePrice(30);

    dayBtns.forEach(btn => {
        btn.addEventListener('click', function() {
            updatePrice(parseInt(this.dataset.days));
        });
    });

    if (limitIpInput) {
        limitIpInput.addEventListener('input', function() {
            updatePrice(parseInt(expiredInput.value || '0', 10));
        });
    }

    usernameInput.addEventListener('input', function() {
        clearTimeout(timeoutId);
        const username = this.value.trim();
        
        if (username.length === 0) {
            feedback.style.display = 'none';
            submitBtn.disabled = false;
            return;
        }

        // Tampilkan pesan loading
        feedback.style.display = 'block';
        feedback.className = 'mt-2 text-warning';
        feedback.textContent = 'Memeriksa ketersediaan username...';
        submitBtn.disabled = true;

        timeoutId = setTimeout(() => {
            fetch(`/api/internal/check-username?username=${encodeURIComponent(username)}`)
                .then(response => response.json())
                .then(data => {
                    if (data.exists) {
                        feedback.className = 'mt-2 text-danger';
                        feedback.textContent = '⛔ Username sudah digunakan. Silakan pilih nama lain.';
                        submitBtn.disabled = true;
                    } else {
                        feedback.className = 'mt-2 text-success';
                        feedback.textContent = '✅ Username tersedia!';
                        submitBtn.disabled = false;
                    }
                })
                .catch(error => {
                    console.error('Error checking username:', error);
                    feedback.className = 'mt-2 text-danger';
                    feedback.textContent = '⚠️ Gagal memeriksa username, coba lagi.';
                    submitBtn.disabled = false;
                });
        }, 500); // Debounce 500ms
    });
});
</script>
@endsection
