@extends('layouts.app')

@section('content')
<div class="container py-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow-sm border-0">
                <div class="card-header bg-white border-0 pt-4 pb-0">
                    <h4 class="fw-bold mb-0 text-uppercase">Buat Akun {{ strtoupper($protocol) }}</h4>
                </div>
                <div class="card-body p-4">
                    @if(session('error'))
                        <div class="alert alert-danger">{{ session('error') }}</div>
                    @endif
                    @if(session('sweet_error'))
                        <div class="alert alert-danger">{{ session('sweet_error') }}</div>
                    @endif
                    @if($errors->any())
                        <div class="alert alert-danger">
                            <ul class="mb-0">
                                @foreach($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <form action="{{ route('vpn.store', $protocol) }}" method="POST" id="createForm">
                        @csrf
                        <div class="mb-3">
                            <label class="form-label fw-bold">Username</label>
                            <input type="text" name="username" id="usernameInput" class="form-control" value="{{ old('username') }}" required>
                            <div class="form-text">Hanya huruf, angka, dot (.), dan underscore (_)</div>
                            <div id="usernameFeedback" class="mt-2" style="display: none; font-weight: bold;"></div>
                        </div>

                        @if($protocol === 'ssh')
                        <div class="mb-3">
                            <label class="form-label fw-bold">Password</label>
                            <input type="text" name="password" class="form-control" value="{{ old('password') }}" required>
                        </div>
                        @else
                        <!-- UUID will be auto-generated by the system -->
                        <input type="hidden" name="password" value="auto">
                        @endif

                        @if($protocol !== 'ssh')
                        <div class="mb-3">
                            <label class="form-label fw-bold">Custom SNI</label>
                            <select name="sni_config" class="form-select">
                                <option value="3" {{ old('sni_config', '3') == '3' ? 'selected' : '' }}>Tanpa konfigurasi (Default)</option>
                                <option value="1" {{ old('sni_config') == '1' ? 'selected' : '' }}>support.zoom.us</option>
                                <option value="2" {{ old('sni_config') == '2' ? 'selected' : '' }}>live.iflix.com</option>
                            </select>
                            <div class="form-text">Pilih profil SNI untuk konfigurasi koneksi.</div>
                        </div>
                        @endif

                        <div class="mb-3">
                            <label class="form-label fw-bold">Masa Aktif (Hari)</label>
                            <input type="number" name="expired" class="form-control" value="{{ old('expired', '30') }}" min="1" max="365" required>
                        </div>

                        @if($protocol !== 'ssh')
                        <div class="mb-3">
                            <label class="form-label fw-bold">Quota (GB)</label>
                            <input type="number" name="quota" class="form-control" value="{{ old('quota', '0') }}" min="0">
                            <div class="form-text">Masukkan 0 untuk unlimited.</div>
                        </div>
                        @endif

                        @if(Auth::user()->role === 'admin')
                        <div class="mb-4">
                            <label class="form-label fw-bold">Limit IP</label>
                            <input type="number" name="limit_ip" class="form-control" value="{{ old('limit_ip', '1') }}" min="1">
                            <div class="form-text">Jumlah maksimal IP yang dapat login bersamaan. Biarkan 1 untuk keamanan.</div>
                        </div>
                        @else
                        <input type="hidden" name="limit_ip" value="1">
                        @endif

                        <div class="d-grid gap-2">
                            <button type="submit" id="submitBtn" class="btn btn-primary btn-lg">Buat Akun</button>
                            <a href="{{ route('vpn.index', $protocol) }}" class="btn btn-light">Kembali</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const usernameInput = document.getElementById('usernameInput');
    const feedback = document.getElementById('usernameFeedback');
    const submitBtn = document.getElementById('submitBtn');
    let timeoutId;

    usernameInput.addEventListener('input', function() {
        clearTimeout(timeoutId);
        const username = this.value.trim();
        
        if (username.length === 0) {
            feedback.style.display = 'none';
            submitBtn.disabled = false;
            return;
        }

        // Tampilkan pesan loading
        feedback.style.display = 'block';
        feedback.className = 'mt-2 text-warning';
        feedback.textContent = 'Memeriksa ketersediaan username...';
        submitBtn.disabled = true;

        timeoutId = setTimeout(() => {
            fetch(`/api/internal/check-username?username=${encodeURIComponent(username)}`)
                .then(response => response.json())
                .then(data => {
                    if (data.exists) {
                        feedback.className = 'mt-2 text-danger';
                        feedback.textContent = '❌ Username sudah digunakan (Mungkin ada di database atau cache). Silakan pilih nama lain.';
                        submitBtn.disabled = true;
                    } else {
                        feedback.className = 'mt-2 text-success';
                        feedback.textContent = '✅ Username tersedia!';
                        submitBtn.disabled = false;
                    }
                })
                .catch(error => {
                    console.error('Error checking username:', error);
                    feedback.className = 'mt-2 text-danger';
                    feedback.textContent = '⚠️ Gagal memeriksa username, coba lagi.';
                    submitBtn.disabled = false;
                });
        }, 500); // Debounce 500ms
    });
});
</script>
@endsection
